import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { TabsNav } from "@/components/layout/TabsNav";
import { ThemeToggle } from "@/components/ui/ThemeToggle";
import { OrdersProvider } from "@/app/orders/OrdersContext";
import { HierarchyProvider } from "@/app/settings/HierarchyContext";
import { UserProvider } from "@/contexts/UserContext";
import { BatchesProvider } from "@/contexts/BatchesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <HierarchyProvider>
            <OrdersProvider>
              <BatchesProvider>
                <Header />
                <div className="flex min-h-screen items-start justify-center bg-background font-sans text-foreground">
                  {/* Main Content */}
                  <main className="container mx-auto px-4 py-6">
                    <div className="flex justify-between">
                      <TabsNav />
                      <ThemeToggle />
                    </div>
                    {children}
                  </main>
                </div>
              </BatchesProvider>
            </OrdersProvider>
          </HierarchyProvider>
        </UserProvider>
      </body>
    </html>
  );
}
